### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by jjmmbb** [sahilph/umbrel-HTTPSizer#6]
When you uninstall HTTPSizer Umbrel come broken. Web access display only a black page. Do you know how to restore backuped files manually?

**Comment by jjmmbb** [comment]
I am able to revert the installation manually. The uninstall script is missing some procedures to rollback everything.

**Comment by sahilph** [comment]
Actually, the app contains a `pre-uninstall` hook which reverts everything to the previous state. But for some reason it never gets executed, I have already created a issue about that https://github.com/getumbrel/umbrel/issues/1918, but I haven't heard back from the developers.
 


>The uninstall script is missing some procedures to rollback everything.
 
Since its a hook, it will only work properly if  it gets executed by the `umbreld` process as it needs some environment variables which the process sets. If you run it directly in the terminal it will not work..

**Comment by sahilph** [comment]
For the time being, I have added a "[Uninstallation Guide](https://github.com/sahilph/umbrel-HTTPSizer/wiki#uninstallation-guide)" , which has steps for uninstalling it manually.

**Comment by jjmmbb** [comment]
> For the time being, I have added a "[Uninstallation Guide](https://github.com/sahilph/umbrel-HTTPSizer/wiki#uninstallation-guide)" , which has steps for uninstalling it manually.

Very good. Thank you.

I have successfully reverted the installation. I will wait for the next update to try to install it again due to Nostr Relay issue.

**Comment by jjmmbb** [comment]
Mysterious... Even uninstalling and installing btcpay, it still redirecting https://.

**Comment by sahilph** [comment]
> I have successfully reverted the installation.

Awesome, I will close this now.
